languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/4.0/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/4.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/4.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source Ui Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /4.0/assets/brand/coreui-social.jpg
  social_logo_path:     /4.0/assets/brand/coreui-social-logo.png

  current_version:      "4.0.3"
  current_ruby_version: "4.0.3"
  docs_version:         "4.0"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  community:            "https://community.coreui.io/"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.0.3.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.0.3/coreui-4.0.3-dist.zip"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.3/dist/css/coreui.min.css"
    css_hash:        "sha384-vG5pwAH63TMfnIplZkih8iaEyVI2isgvS6sWg7DOW0rXYeF89XOblOh/0EvsnP1X"
    css_rtl:         "https://cdn.jsdelivr.net/npm/coreui@4.0.3/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-E8evvROTle0BDVjyCp4x0o8ZNBoUKOPm1IJRHoFdbMhF6Bf7fVmKsEfttS7ZfKSI"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.3/dist/js/coreui.min.js"
    js_hash:         "sha384-KX4skdrGsSAH7RtuUgcyis7N+SZcp6/7nhEgCEbywKdvGzip+RZxaxQRONMRxQow"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@4.0.3/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-48mjpThYfYG1nJRyyMAvJ5mnGJCG7D+MTDf/7E+gxTGvMg1Qk5Js8CLQG+ZyF5VV"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    popper_hash:      "sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN"
