languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/4.0/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/4.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/4.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source Ui Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /4.0/assets/brand/coreui-social.jpg
  social_logo_path:     /4.0/assets/brand/coreui-social-logo.png

  current_version:      "4.0.0-alpha.0"
  current_ruby_version: "4.0.0-alpha.0"
  docs_version:         "4.0"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  community:            "https://community.coreui.io/"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui/archive/v4.0.0-alpha.0.zip"
    dist:               "https://github.com/coreui/coreui/releases/download/v4.0.0-alpha.0/coreui-4.0.0-alpha.0-dist.zip"

  cdn:
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/css/coreui.min.css"
    css_hash:        "sha384-Rxg5cYTZqXcMAFzxa3dkLGYBjDVqg/w6Xg8x8sJoW4gxhhcGHbvTZ5S99kJ8NokU"
    css_rtl:         "https://cdn.jsdelivr.net/npm/coreui@4.0.0-alpha.0/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-OkY56leSb/dcwfOPXfjmD/6eTguTFY42H/XLzYrykzc9DsUgytcACdtG4vLFdNv+"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/js/coreui.min.js"
    js_hash:         "sha384-auMQVU9h2wHVjeICVw06fZd/Bwu89wUtkbfvQdFUVKmdFyKmJno12PpjJdiyKXjj"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui@3.3.0/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-QhgYN4WY6/5h5VonldJJYUyvf2UPweJFd7leRtB7uSm3sisWLYKpDrwfk9Kvj+C9"
    popper:          "https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"
    popper_hash:     "sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
