languageCode:           "en"
title:                  "CoreUI"
baseURL:                "https://coreui.io/docs/"
canonifyURLs:           true

security:
  enableInlineShortcodes: true
  funcs:
    getenv:
      - ^HUGO_
      - NETLIFY

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
  tableOfContents:
    startLevel:         2
    endLevel:           6

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "term", "RSS"]

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/dist
    - source:           docs/assets
      target:           assets
    - source:           docs/content
      target:           content
    - source:           docs/data
      target:           data
    - source:           docs/layouts
      target:           layouts
    - source:           docs/static
      target:           static
    - source:           docs/static/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           docs/static/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "Open Source UI Components library built on top of Bootstrap 5."
  authors:              "Lukasz Holeczek, Andrzej Kopanski"
  social_image_path:    /assets/brand/coreui-social.jpg
  social_logo_path:     /assets/brand/coreui-social-logo.png

  current_version:      "4.2.1"
  current_ruby_version: "4.2.1"
  docs_version:         "4.2"
  rfs_version:          "9.0.3"
  github_org:           "https://github.com/coreui"
  repo:                 "https://github.com/coreui/coreui"
  twitter:              "core_ui"
  community:            "https://github.com/coreui/coreui/discussions"
  blog:                 "https://coreui.io/blog/"
  icons:                "https://icons.coreui.io/"

  download:
    source:             "https://github.com/coreui/coreui-pro/archive/v4.2.1.zip"
    dist:               "https://github.com/coreui/coreui-pro/releases/download/v4.2.1/coreui-4.2.1-dist.zip"

  cdn:
  # See https://www.srihash.org for info on how to generate the hashes
    css:             "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.2.1/dist/css/coreui.min.css"
    css_hash:        "sha384-q0Ja96GxuKqNEh7KDLa79pu47abmS0a2pZpPREKd5ZPlutD+GEJI/Jhe5SXkr5mr"
    css_rtl:         "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.2.1/dist/css/coreui.rtl.min.css"
    css_rtl_hash:    "sha384-lWtBKdsf+TSW4U+aNdCFdoq25QG0GUbtYkK6L8V7sVZrl5lh6DbT3A+9G/7WFsrz"
    js:              "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.2.1/dist/js/coreui.min.js"
    js_hash:         "sha384-FI3ZcGr5XHHHMfE5DC/gMVe03mmQB8MxeP3No4FUxOrL3a9qvDedrviBTkX+qHtz"
    js_bundle:       "https://cdn.jsdelivr.net/npm/@coreui/coreui-pro@4.2.1/dist/js/coreui.bundle.min.js"
    js_bundle_hash:  "sha384-buYULMZH2OycNNKg+mmxa2waaFcciDgcA0Gd8CBDU+/Afub3TONdYMWYN0AgLuLS"
    popper:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
    popper_hash:      "sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
